-- FS25_OuttaMyWay v4.7.12 Field World equivalence evidence.
-- Canonical architecture authority: v4.6.78.

OuttaMyWay = OuttaMyWay or {}
OuttaMyWay.MOD_NAME = g_currentModName or "FS25_OuttaMyWay"
OuttaMyWay.VERSION = "4.7.12"
OuttaMyWay.ARCHITECTURE_VERSION = "4.6.78"
OuttaMyWay.RUNTIME_MODE = "FIELD_WORLD_EQUIVALENCE_EVIDENCE"
OuttaMyWay.CONTROL_AUTHORITY_ENABLED = false
OuttaMyWay.PASSIVE_SAMPLE_INTERVAL_MS = 1000
OuttaMyWay.PASSIVE_HEARTBEAT_INTERVAL_MS = 10000
OuttaMyWay.PASSIVE_FUTURE_HORIZON_SECONDS = 10

OuttaMyWay.FIELD_IDENTITY_PROBE_HEARTBEAT_INTERVAL_MS = 10000

OuttaMyWay.FIELD_WORLD_SNAPSHOT_GENERATION_BUDGET = 0.00025
OuttaMyWay.FIELD_WORLD_FINGERPRINT_QUANTIZATION_METRES = 0.1
OuttaMyWay.FIELD_WORLD_FINGERPRINT_VERSION = "FWG1"

OuttaMyWay.FIELD_WORLD_EQUIVALENCE_SAMPLE_SIDE = 31
OuttaMyWay.FIELD_WORLD_EQUIVALENCE_MAX_REFERENCE_SNAPSHOTS = 16
OuttaMyWay.FIELD_WORLD_EQUIVALENCE_MAX_STORED_SNAPSHOTS = 32
OuttaMyWay.FIELD_WORLD_EQUIVALENCE_MAX_COMPARISONS = 128
