local M={}
local mandatory={"FIELD_WORLD_CONTAINMENT","TRANSITION_CLEARANCE","REPRESENTATION_FITNESS","CONTROL_CAPABILITY_AVAILABILITY","CONTINUING_INTENT_PRIORITY","PROGRESS_PRESERVATION","RESPONSIBILITY_COMPATIBILITY","OBLIGATION_COMPATIBILITY","COMMITMENT_PRECONDITIONS","EFFECTIVE_ACTUATION_COMPOSITION","SAFE_RELEASE_HANDOVER"}
local function evidence(overrides)
    local result={}
    for _,id in ipairs(mandatory) do result[id]={result="PASS",evidence={documented=true},provenance={source="canonical-documentation"},reason="documented reconstruction supports constraint",revalidationTrigger={kind="FIXTURE_CHANGE"}} end
    for id,value in pairs(overrides or {}) do result[id]=value end
    return result
end
local function candidate(referenceKey,capability,cost,options)
    options=options or {}
    return {
        referenceKey=referenceKey,purpose={kind=options.purpose or "SAFE_CONTINUATION",referenceKey=referenceKey},subject={assemblyId=options.assemblyId or "AS-A"},capability=capability,
        expectedEffect={kind=capability},evidenceBasis={constraintEvidence=evidence(options.constraints),governingBasis=options.governingBasis,progressActuationOwnership=options.progressActuationOwnership,effectiveActuationComposition=options.composition,responsibilityException=options.responsibilityException,maintainsExistingCommitment=options.maintainsExistingCommitment},
        representationFitness={requirements=options.fitnessRequirements or {}},preconditions=options.preconditions or {facts={}},invalidationConditions={{kind="OPERATIONAL_PICTURE_CHANGE"}},reversibility={reversible=capability~="ESCALATE"},
        obligationsCreated=options.obligations or {},releaseImplications=options.releaseImplications or {required=false},uncertainty=options.uncertainty or {},comparisonCost=cost
    }
end
local function picture(identity,specs,options)
    options=options or {}
    return {
        identity=identity,epoch=options.epoch or 100,observationSnapshotId="OS-"..identity,
        situations={{identity="SI-"..identity,operationId="OR-1",memberAssemblyIds={"AS-A","AS-B"},relevantAssemblyIds={"AS-A","AS-B"},provenance={source="documented-reconstruction"}}},
        encounters={{identity="EN-"..identity,operationId="OR-1",subjectAssemblyId="AS-A",otherAssemblyId="AS-B",relationship="FUTURE_SPACE_CONVERGENCE",evidence={source="documented-reconstruction"}}},
        identities={assemblies={"AS-A","AS-B"},components={},jobEpisodes={active={"JE-A","JE-B"},admitted={},ended={}},operations={active={"OR-1"},ended={}}},
        currentSpace={},futureSpace={},demand={committedDemand={},potentialDemand={},temporarySlack={}},responsibilityRelations=options.responsibilityRelations or {},uncertainty=options.uncertainty or {},representationFitness=options.representationFitness or {},
        provenance={source="documented-historical-reconstruction",fixture=identity},controlOutcomeEvidence={},
        candidateSupportEvidence={complete=true,supportBoundary={kind="DOCUMENTED_HISTORICAL_RECONSTRUCTION",capabilityBoundary=options.capabilityBoundary or {}},candidateSpecifications=specs,provenance={source="canonical-documentation"}},
        commitmentContext=options.commitmentContext or {}
    }
end
local function obligation(kind,class)
    return {origin={kind=kind},basis={kind=kind},requiredOutcome={kind=kind},requiredAuthority={},evidenceContract={kind="OBSERVED_"..kind},ownershipClass=class or "ORIGIN_BOUND",transferPolicy={allowed=false},terminalDependency=true,creationEvidence={source="canonical-documentation"}}
end

M.fixtures={
OuttaMyWay.ReplayFixture.new({identity="RF-NO-MOD",title="No-mod control",sourceEvidence={{document="REPLAY_VALIDATION_SPECIFICATION.md",family="no-mod control"}},steps={{kind="NO_ACTIVITY",expect={activityCount=0}}},expected={classification="CONTROL"},provenance={reconstruction="METADATA_ONLY"}}),
OuttaMyWay.ReplayFixture.new({identity="RF-LOADED-NO-ENCOUNTER",title="Loaded mod with no Encounter",sourceEvidence={{document="REPLAY_VALIDATION_SPECIFICATION.md",family="loaded/no-encounter control"}},steps={{kind="PROCESS_OBSERVATION",input={raw={timestamp=1,provenance={source="control"},fieldWorld={referenceKey="field-world-control",fieldPolygonReferenceKey="field-control",operationMembershipEvidenceComplete=true},assemblies={},geometry={},motion={},aiStates={},playerControl={},jobEpisodeEvidence={},operationMembershipEvidence={},physicalRepresentationEvidence={},controlOutcomes={},unavailableSources={}}},expect={encounterCount=0,situationCount=0,commitmentCount=0}}},expected={classification="NO_ACTIVITY"},provenance={reconstruction="SEALED_CONTROL"}}),
OuttaMyWay.ReplayFixture.new({identity="RF-V4649",title="v4.6.49 local passage evidence",sourceEvidence={{document="ARCHITECTURE_COMPLIANCE_AUDIT_V4.6.49.md",fact="admissibility before optimisation passed locally"}},steps={
    {kind="EVALUATE_PICTURE",alias="decision",input={picture=picture("V4649",{
        candidate("cheap-unclear","CONTINUE_UNCHANGED",0,{constraints={TRANSITION_CLEARANCE={result="FAIL",evidence={},provenance={},reason="documented local path not clear",revalidationTrigger={}}}}),
        candidate("clear-reposition","REPOSITION",10,{assemblyId="AS-A",governingBasis={responsibilityKey="V4649-LOCAL-PASSAGE",operationId="OR-1",jobEpisodeIds={"JE-A","JE-B"}},progressActuationOwnership={assemblyIds={"AS-A"}},composition={identity="EC-V4649",epoch=1,relevantAssemblyIds={"AS-A","AS-B"},entries={{assemblyId="AS-A",commitmentId="PROPOSED",capability="REPOSITION",effectClass="MOVEMENT",progressActuation=true}}},responsibilityException={result="PASS",reason="documented bounded fixture authority",evidence={bounded=true},provenance={source="audit"}},fitnessRequirements={{representationId="REP-A",acceptedStates={"CURRENTLY_FIT"}}},obligations={obligation("SAFE_RELEASE")}})
    },{representationFitness={{representationId="REP-A",assemblyId="AS-A",question="REPOSITION",assessmentHorizon=5,state="CURRENTLY_FIT",claimPermissions={"REPOSITION"},coverage={complete=true,conservative=true},uncertainty={},validityDependencies={},provenance={}}}})},expect={selectedCapability="REPOSITION",decisionAction="CREATE",viableCount=1}},
    {kind="APPLY_DECISION",input={decisionResult="$decision"},expect={action="CREATE",resultingState="ACTIVE",createdObligationCount=1,authorityTokenCount=1,commitmentCount=1}}
},expected={classification="POSITIVE_CAPABILITY_EVIDENCE"},provenance={reconstruction="DOCUMENTED_FACTS_ONLY"}}),
OuttaMyWay.ReplayFixture.new({identity="RF-V4657",title="v4.6.57 bundled handback freeze line",sourceEvidence={{document="ADR-0007",fact="bundled restoration release and continuation disproved"}},steps={
    {kind="CREATE_COMMITMENT",alias="commitment",input={values={objective={kind="RECOVERY"},governingBasis={responsibilityKey="V4657-RECOVERY"},obligationSpecifications={obligation("CONFIGURATION_RESTORATION")}}},expect={state="ACTIVE",obligationCount=1}},
    {kind="EVALUATE_PICTURE",alias="decision",input={picture=picture("V4657",{candidate("bundled-handover","HANDOVER_TO_GIANTS",1,{composition={identity="EC-V4657",epoch=1,relevantAssemblyIds={"AS-A","AS-B"},entries={{assemblyId="AS-A",commitmentId="$commitment.commitment.identity",capability="HANDOVER_TO_GIANTS",effectClass="HANDOVER",progressActuation=true}}},constraints={SAFE_RELEASE_HANDOVER={result="UNRESOLVED",evidence={bundled=true},provenance={source="ADR-0007"},reason="stable restoration and continuation evidence absent",revalidationTrigger={kind="RESTORATION_EVIDENCE"}}}})}, {commitmentContext={{commitmentId="$commitment.commitment.identity"}}})},expect={decisionAction="WAIT",nonInterventionClass="WAIT_FOR_EVIDENCE",viableCount=0}},
    {kind="APPLY_DECISION",input={decisionResult="$decision"},expect={action="WAIT",previousState="ACTIVE",resultingState="WAITING_FOR_EVIDENCE"}}
},expected={classification="DISPROVED_BUNDLED_HANDOFF"},provenance={reconstruction="DOCUMENTED_FACTS_ONLY"}}),
OuttaMyWay.ReplayFixture.new({identity="RF-V4664",title="v4.6.64 recovery and Native Handover",sourceEvidence={{document="ADR-0011",fact="primary recovery handover and independent continuation passed"}},steps={
    {kind="CREATE_COMMITMENT",alias="commitment",input={values={objective={kind="RECOVERY"},governingBasis={responsibilityKey="V4664-RECOVERY"},progressAssemblyIds={"AS-A"},obligationSpecifications={obligation("CONFIGURATION_INTEGRITY"),obligation("INDEPENDENT_CONTINUATION"),obligation("SAFE_RELEASE")}}},expect={state="ACTIVE",obligationCount=3,authorityTokenCount=1}},
    {kind="EVALUATE_PICTURE",alias="revise",input={picture=picture("V4664-LEG2",{candidate("next-manoeuvre-leg","REPOSITION",1,{assemblyId="AS-A",maintainsExistingCommitment=false,composition={identity="EC-V4664-LEG2",epoch=2,relevantAssemblyIds={"AS-A","AS-B"},entries={{assemblyId="AS-A",commitmentId="$commitment.commitment.identity",capability="REPOSITION",effectClass="MOVEMENT",progressActuation=true}}},fitnessRequirements={{representationId="REP-A",acceptedStates={"CURRENTLY_FIT"}}}})},{commitmentContext={{commitmentId="$commitment.commitment.identity"}},representationFitness={{representationId="REP-A",assemblyId="AS-A",question="REPOSITION",assessmentHorizon=5,state="CURRENTLY_FIT",claimPermissions={"REPOSITION"},coverage={complete=true,conservative=true},uncertainty={},validityDependencies={},provenance={}}}})},expect={selectedCapability="REPOSITION",decisionAction="REVISE"}},
    {kind="APPLY_DECISION",alias="application",input={decisionResult="$revise"},expect={action="REVISE",commitmentId="$commitment.commitment.identity",resultingState="ACTIVE",commitmentCount=1}},
    {kind="GOVERNING_BASIS_EVENT",alias="settling",input={commitmentId="$commitment.commitment.identity",event={kind="OBJECTIVE_SATISFIED",evidence={nativeHandover=true,independentContinuation=true},provenance={source="ADR-0011"}}},expect={invalidated=true,state="SETTLING",intendedTerminalDisposition="SUCCEEDED",releasedAuthorityCount=1,openObligationCount=3}},
    {kind="SETTLE_OBLIGATION",input={obligationId="$commitment.obligationIds.1",mode="SATISFACTION",evidence={configurationIntegrity=true}},expect={status="SETTLED"}},
    {kind="SETTLE_OBLIGATION",input={obligationId="$commitment.obligationIds.2",mode="SATISFACTION",evidence={independentContinuation=true}},expect={status="SETTLED"}},
    {kind="SETTLE_OBLIGATION",input={obligationId="$commitment.obligationIds.3",mode="SATISFACTION",evidence={safeRelease=true}},expect={status="SETTLED"}},
    {kind="ATTEMPT_TERMINAL",input={commitmentId="$commitment.commitment.identity",evidence={terminalSettlementPoint="SAFE_RELEASE"}},expect={state="SUCCEEDED",openObligationCount=0}}
},expected={classification="POSITIVE_COMPLETE_LIFECYCLE"},provenance={reconstruction="DOCUMENTED_FACTS_ONLY"}}),
OuttaMyWay.ReplayFixture.new({identity="RF-V4670",title="v4.6.70 Hold-release failure",sourceEvidence={{document="ADR-0017",fact="cruise ceiling and universal non-closing release model rejected"}},steps={
    {kind="CREATE_COMMITMENT",alias="commitment",input={values={objective={kind="HOLD_RELEASE"},governingBasis={responsibilityKey="V4670-HOLD"},obligationSpecifications={obligation("SAFE_RELEASE")}}},expect={state="ACTIVE",obligationCount=1}},
    {kind="EVALUATE_PICTURE",alias="decision",input={picture=picture("V4670",{candidate("release-hold","HANDOVER_TO_GIANTS",1,{constraints={SAFE_RELEASE_HANDOVER={result="UNRESOLVED",evidence={nativeSpeedSource="CRUISE_CEILING"},provenance={source="ADR-0017"},reason="counterfactual native continuation unsupported",revalidationTrigger={kind="NATIVE_CONTINUATION_EVIDENCE"}}},composition={identity="EC-V4670",epoch=1,relevantAssemblyIds={"AS-A","AS-B"},entries={{assemblyId="AS-A",commitmentId="$commitment.commitment.identity",capability="HANDOVER_TO_GIANTS",effectClass="RELEASE",progressActuation=false}}}})},{commitmentContext={{commitmentId="$commitment.commitment.identity"}}})},expect={decisionAction="WAIT",nonInterventionClass="WAIT_FOR_EVIDENCE",viableCount=0}},
    {kind="APPLY_DECISION",input={decisionResult="$decision"},expect={action="WAIT",resultingState="WAITING_FOR_EVIDENCE"}},
    {kind="REGISTRY_STATUS",input={commitmentId="$commitment.commitment.identity"},expect={commitmentState="WAITING_FOR_EVIDENCE",openObligationCount=1,progressAuthorityCount=0}}
},expected={classification="REJECTED_RELEASE_MODEL"},provenance={reconstruction="DOCUMENTED_FACTS_ONLY"}}),
OuttaMyWay.ReplayFixture.new({identity="RF-V4677",title="v4.6.77 illegal completion at t=209.3s",sourceEvidence={{document="ARCHITECTURE_COMPLIANCE_AUDIT_V4.6.77.md",fact="safeRelease=false completion and duplicate Commitment"}},steps={
    {kind="CREATE_COMMITMENT",alias="commitment",input={values={objective={kind="RECOVERY"},governingBasis={responsibilityKey="V4677-RECOVERY"},obligationSpecifications={obligation("SAFE_RELEASE")}}},expect={state="ACTIVE",obligationCount=1,commitmentCount=1}},
    {kind="GOVERNING_BASIS_EVENT",input={commitmentId="$commitment.commitment.identity",event={kind="OBJECTIVE_SATISFIED",evidence={nativeHandover=true,safeRelease=false,architectureTime=209.3},provenance={source="v4.6.77 audit"}}},expect={state="SETTLING",intendedTerminalDisposition="SUCCEEDED",openObligationCount=1}},
    {kind="ATTEMPT_TERMINAL",input={commitmentId="$commitment.commitment.identity",evidence={safeRelease=false}},expectErrorContains="obligations remain open"},
    {kind="CREATE_COMMITMENT",input={values={objective={kind="RECOVERY_RELABELED"},governingBasis={responsibilityKey="V4677-RECOVERY"}}},expectErrorContains="unresolved responsibility already owned"},
    {kind="REGISTRY_STATUS",input={commitmentId="$commitment.commitment.identity"},expect={commitmentCount=1,commitmentState="SETTLING",openObligationCount=1}}
},expected={classification="NEGATIVE_LIFECYCLE_REGRESSION"},provenance={reconstruction="DOCUMENTED_FACTS_ONLY"}}),
OuttaMyWay.ReplayFixture.new({identity="RF-TS016",title="TS016 crossing and head-on responsibility",sourceEvidence={{document="REPLAY_VALIDATION_SPECIFICATION.md",family="TS016 crossing/head-on"},{document="canonical architecture",fact="Follower Owns Closure"}},steps={
    {kind="EVALUATE_PICTURE",alias="decision",input={picture=picture("TS016",{
        candidate("leader-reposition","REPOSITION",1,{assemblyId="AS-A",composition={identity="EC-TS016-L",epoch=1,relevantAssemblyIds={"AS-A","AS-B"},entries={{assemblyId="AS-A",commitmentId="PROPOSED",capability="REPOSITION",effectClass="MOVEMENT",progressActuation=true}}},fitnessRequirements={{representationId="REP-A",acceptedStates={"CURRENTLY_FIT"}}}}),
        candidate("follower-regulate","REGULATE_SPEED",2,{assemblyId="AS-B",governingBasis={responsibilityKey="TS016-CLOSURE"},progressActuationOwnership={assemblyIds={"AS-B"}},composition={identity="EC-TS016-F",epoch=1,relevantAssemblyIds={"AS-A","AS-B"},entries={{assemblyId="AS-B",commitmentId="PROPOSED",capability="REGULATE_SPEED",effectClass="SPEED",progressActuation=true}}},fitnessRequirements={{representationId="REP-B",acceptedStates={"CURRENTLY_FIT"}}}})
    },{responsibilityRelations={{relation="FOLLOWER_OWNS_CLOSURE",followerAssemblyId="AS-B",leaderAssemblyId="AS-A",closingRate=1,horizon=5,provenance={source="canonical"}}},representationFitness={{representationId="REP-A",assemblyId="AS-A",question="REPOSITION",assessmentHorizon=5,state="CURRENTLY_FIT",claimPermissions={"REPOSITION"},coverage={complete=true,conservative=true},uncertainty={},validityDependencies={},provenance={}},{representationId="REP-B",assemblyId="AS-B",question="REGULATE_SPEED",assessmentHorizon=5,state="CURRENTLY_FIT",claimPermissions={"SPEED"},coverage={complete=true,conservative=true},uncertainty={},validityDependencies={},provenance={}}}})},expect={selectedCapability="REGULATE_SPEED",decisionAction="CREATE",["verdicts.leader-reposition:RESPONSIBILITY_COMPATIBILITY"]="FAIL"}},
    {kind="APPLY_DECISION",input={decisionResult="$decision"},expect={action="CREATE",resultingState="ACTIVE",authorityTokenCount=1}}
},expected={classification="RESPONSIBILITY_ENFORCEMENT"},provenance={reconstruction="CANONICAL_CONTRACT"}}),
OuttaMyWay.ReplayFixture.new({identity="RF-PLAYER-TAKEOVER",title="Player takeover responsibility continuity",sourceEvidence={{document="ADR-0019",fact="player takeover ends progress authority but not internal obligations"}},steps={
    {kind="CREATE_COMMITMENT",alias="commitment",input={values={objective={kind="COORDINATION"},governingBasis={responsibilityKey="PLAYER-TAKEOVER"},progressAssemblyIds={"AS-A"},obligationSpecifications={obligation("COORDINATION_CONTINUITY","CONTINUITY")}}},expect={state="ACTIVE",authorityTokenCount=1,obligationCount=1}},
    {kind="GOVERNING_BASIS_EVENT",input={commitmentId="$commitment.commitment.identity",event={kind="PLAYER_TAKEOVER",evidence={assemblyId="AS-A"},provenance={source="ADR-0019"}}},expect={state="SETTLING",intendedTerminalDisposition="CANCELLED_BY_SOURCE_INTENT_TERMINATION",releasedAuthorityCount=1,openObligationCount=1}},
    {kind="REGISTRY_STATUS",input={commitmentId="$commitment.commitment.identity"},expect={commitmentState="SETTLING",openObligationCount=1,progressAuthorityCount=0}}
},expected={classification="PLAYER_EXTERNAL_AGENCY"},provenance={reconstruction="CANONICAL_CONTRACT"}}),
OuttaMyWay.ReplayFixture.new({identity="RF-OPERATION-ZERO",title="Operation termination with origin-bound remnant",sourceEvidence={{document="ADR-0019",fact="zero membership does not erase origin-bound obligations"}},steps={
    {kind="CREATE_COMMITMENT",alias="commitment",input={values={objective={kind="SETTLEMENT"},governingBasis={responsibilityKey="OPERATION-ZERO"},obligationSpecifications={obligation("CONTROL_RECONCILIATION","ORIGIN_BOUND")}}},expect={state="ACTIVE",obligationCount=1}},
    {kind="GOVERNING_BASIS_EVENT",input={commitmentId="$commitment.commitment.identity",event={kind="OPERATION_TERMINATED",evidence={membershipCount=0},provenance={source="ADR-0019"}}},expect={state="SETTLING",intendedTerminalDisposition="CANCELLED_BY_OPERATION_TERMINATION",openObligationCount=1}},
    {kind="ATTEMPT_TERMINAL",input={commitmentId="$commitment.commitment.identity",evidence={membershipCount=0}},expectErrorContains="obligations remain open"}
},expected={classification="ORIGIN_BOUND_CONTINUITY"},provenance={reconstruction="CANONICAL_CONTRACT"}})
}
return M
